"""initial schema with multi-tenancy

Revision ID: 3c68e15e6b50
Revises: 
Create Date: 2025-12-02 19:37:24.190751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c68e15e6b50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('cor_calendario', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_turno_id'), 'tipos_turno', ['id'], unique=False)
    op.create_index(op.f('ix_tipos_turno_nome'), 'tipos_turno', ['nome'], unique=False)
    op.create_index(op.f('ix_tipos_turno_telegram_user_id'), 'tipos_turno', ['telegram_user_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('numero_funcionario', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_numero_funcionario'), 'usuarios', ['numero_funcionario'], unique=True)
    op.create_index(op.f('ix_usuarios_telegram_user_id'), 'usuarios', ['telegram_user_id'], unique=True)
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('tipo_turno_id', sa.Integer(), nullable=True),
    sa.Column('tipo_livre', sa.String(length=50), nullable=True),
    sa.Column('descricao_opcional', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_turno_id'], ['tipos_turno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnos_data_referencia'), 'turnos', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_turnos_id'), 'turnos', ['id'], unique=False)
    op.create_index(op.f('ix_turnos_telegram_user_id'), 'turnos', ['telegram_user_id'], unique=False)
    op.create_table('integracao_calendario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('provedor', sa.String(length=50), nullable=False),
    sa.Column('event_uid', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integracao_calendario_id'), 'integracao_calendario', ['id'], unique=False)
    op.create_index(op.f('ix_integracao_calendario_turno_id'), 'integracao_calendario', ['turno_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integracao_calendario_turno_id'), table_name='integracao_calendario')
    op.drop_index(op.f('ix_integracao_calendario_id'), table_name='integracao_calendario')
    op.drop_table('integracao_calendario')
    op.drop_index(op.f('ix_turnos_telegram_user_id'), table_name='turnos')
    op.drop_index(op.f('ix_turnos_id'), table_name='turnos')
    op.drop_index(op.f('ix_turnos_data_referencia'), table_name='turnos')
    op.drop_table('turnos')
    op.drop_index(op.f('ix_usuarios_telegram_user_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_numero_funcionario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipos_turno_telegram_user_id'), table_name='tipos_turno')
    op.drop_index(op.f('ix_tipos_turno_nome'), table_name='tipos_turno')
    op.drop_index(op.f('ix_tipos_turno_id'), table_name='tipos_turno')
    op.drop_table('tipos_turno')
    # ### end Alembic commands ###
