"""create signatures table

Revision ID: 77905a838e45
Revises: 952baee58d3b
Create Date: 2025-12-02 19:51:44.764819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77905a838e45'
down_revision: Union[str, Sequence[str], None] = '952baee58d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plano', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assinaturas_id'), 'assinaturas', ['id'], unique=False)
    op.create_index(op.f('ix_assinaturas_stripe_customer_id'), 'assinaturas', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_assinaturas_stripe_subscription_id'), 'assinaturas', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_assinaturas_telegram_user_id'), 'assinaturas', ['telegram_user_id'], unique=True)
    # ### end Alembic commands ###
    
    # ✅ Habilitar RLS na tabela assinaturas
    op.execute("""
        ALTER TABLE assinaturas ENABLE ROW LEVEL SECURITY;
    """)
    
    # ✅ Política para assinaturas: usuário só vê sua própria assinatura
    op.execute("""
        CREATE POLICY assinaturas_isolation ON assinaturas
        USING (telegram_user_id = NULLIF(current_setting('app.current_user_id', TRUE), '')::BIGINT);
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assinaturas_telegram_user_id'), table_name='assinaturas')
    op.drop_index(op.f('ix_assinaturas_stripe_subscription_id'), table_name='assinaturas')
    op.drop_index(op.f('ix_assinaturas_stripe_customer_id'), table_name='assinaturas')
    op.drop_index(op.f('ix_assinaturas_id'), table_name='assinaturas')
    op.drop_table('assinaturas')
    # ### end Alembic commands ###
